spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rinha
    password: postgres
    username: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        order_updates: true
        order_inserts: true
        batch_versioned_data: true
        jdbc:
          batch_size: 50
  threads:
    virtual:
      enabled: true

server:
  port: ${API_PORT:8080}