spring:
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/rinha}
    password: ${DB_PASSWORD:postgres}
    username: ${DB_USERNAME:postgres}
    hikari:
      maximum-pool-size: 10
  jpa:
    show-sql: false
    properties:
      hibernate:
        order_updates: true
        order_inserts: true
        batch_versioned_data: true
        jdbc:
          batch_size: 50
  threads:
    virtual:
      enabled: true

server:
  port: ${API_PORT:8080}