version: "3.5"

services:
  api01:
    image: rinha-back-end:latest
    hostname: api01
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/rinha
      - DB_PASSWORD=123
      - DB_USERNAME=admin
      - JMX_PORT=9001
    ports:
      - "8081:8080"
      - "9001:9001"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "200MB"
  api02:
    image: rinha-back-end:latest
    hostname: api02
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/rinha
      - DB_PASSWORD=123
      - DB_USERNAME=admin
      - JMX_PORT=9002
    ports:
      - "8082:8080"
      - "9002:9002"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "200MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10MB"

  db:
    image: postgres:16-alpine
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
#    command: 'postgres -c max_connections=30 -p 5432'
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "140MB"
networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1